#!/bin/bash

gcc main.c

echo Left
cat lorem.txt | ./a.out --left
echo

echo Center
cat lorem.txt | ./a.out --center
echo

echo Right
cat lorem.txt | ./a.out --right
echo

echo Border Left
cat lorem.txt | ./a.out --border --left
echo

echo Border Center
cat lorem.txt | ./a.out --border --center
echo

echo Border Right
cat lorem.txt | ./a.out --border --right
